SRC=/home/darryl/Development/kmerge/src
HOME_DIR=/home/darryl
CXX=/home/darryl/hdf5/bin/h5c++ 
CXX+=-W -Wall -Wno-long-long -pedantic -Wno-variadic-macros 
LDFLAGS+=-L/home/darryl/lib -lm -lz -lrt -lsz
CXXFLAGS += -I $(HOME_DIR)/include -I $(HOME_DIR)/hdf5/include -D_NOMPI
CXXFLAGS += -I $(HOME_DIR)/Development/include -I $(HOME_DIR)/Development/seqan-trunk/core/include -I $(HOME_DIR)/Development/seqan-trunk/extras/include

default: all
all: kmerge

kmerge: main.o
	$(CXX) $(LDFLAGS) main.o kmerge.o -o kmerge

main.o: kmerge.o $(SRC)/main.cc
	$(CXX) $(CXXFLAGS) kmerge.o -c $(SRC)/main.cc $(LDFLAGS)

kmerge.o: $(SRC)/kmerge.h $(SRC)/kmerge.cc
	$(CXX) $(CXXFLAGS) -c $(SRC)/kmerge.cc $(LDFLAGS)

clean:
	rm -f main.o main kmerge.o kmerge

.PHONY: default all clean