# get_genomes.py
# perl ../scripts/contiguous_fasta.pl <(zcat genome.test.fa.gz) | ~/bin/fastx_toolkit/bin/fasta_formatter -w 80 | gzip > genome.test.contig.fa.gz

# for FASTQ

# perl ../scripts/contiguous_fasta.pl <(zcat sample.fastq.gz | ~/fastx_toolkit/bin/fastq_to_fasta -Q33) | ~/bin/fastx_toolkit/bin/fasta_formatter -w 80 | gzip > sample.contig.fa.gz